language: node_js
node_js:
  - node
env:
  global:
    - CC_TEST_REPORTER_ID=eb741625da4b075b0e129b8f04cc5a6b050552fa38118f5d924c76a2232a8255
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 
notifications:
  email: false